// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgxuejlkvupzjagjgjwc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBneHVlamxrdnVwemphZ2pnandjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MzgwOTksImV4cCI6MjA2NTQxNDA5OX0.up6NovD17kMnkSqE4SnKKxorgJOPLOpVWSoJNU0bQeU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);